config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :book_requests do
    collection do
      post 'approve'
      post 'reject'
    end
  end
  resources :universities
  resources :book_counts
  resources :book_histories do
    collection do
      get 'overdue_fines'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  resources :students
  resources :librarians do
    member do
      get 'approve'
    end
  end
  resources :libraries
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'book_histories/:id/return', to: 'book_histories#return_book'

  root 'home#index'
  # redirecting all undefined routes to homepage for now
  # this prevents the javascript file from being dynamically generated
  # will have to search for another alternative
  # get '*path', to: 'home#index'

  get 'home/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'set_google_signup_user_type', to: 'sessions#set_google_signup_user_type'

  get 'javascripts/dynamic_libraries'

  get '/privacy' => "privacy#show"

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # Redirecting non existing routes to
  get "*path", to: redirect('/')

end

app/models/library.rb
class Library < ApplicationRecord
  has_many :librarians,
           :dependent => :delete_all
  has_many :book_counts,
           :dependent => :delete_all
  has_many :book_requests,
           :dependent => :delete_all
  has_many :book_histories,
           :dependent => :delete_all
  belongs_to :university

  validates :name,
            :presence => true
  validates :location,
            :presence => true
  validates :max_days,
            :presence => true,
            :numericality => {greater_than: 0}
  validates :overdue_fine,
            :presence => true,
            :numericality => {greater_than: 0}
  validates :university_id,
            :presence => true

  def self.check_if_authorised?(user_type, user_id, library_id);
    case user_type
    when ApplicationController::TYPE_STUDENT
      libraries = Library.where(:university_id => Student.find(user_id).university_id).collect{|x| x.id};
      return libraries.include?(library_id.to_i);
    when ApplicationController::TYPE_LIBRARIAN
      return Librarian.find(user_id).library_id == library_id.to_i
    end
  end

  def self.delete(library_id)
    # increment student book limits
    BookHistory.increment_student_limits_by_books_issued_by_library(library_id)
    Library.destroy(library_id)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /libraries
  # GET /libraries.json
  def index
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      @libraries = Library.where(:university_id => current_user.university_id)
    when ApplicationController::TYPE_LIBRARIAN
      # TODO: what exactly needs to be done here?
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    when ApplicationController::TYPE_ADMIN
      @libraries = Library.all
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_ADMIN
      # admin can see any library
    else
      check = Library.check_if_authorised?(user_type, current_user.id, params[:id]);
      if (check == false)
        flash[:notice] = "You are not authorised to perform this action"
        redirect_to root_path
      end
    end
  end

  # GET /libraries/new
  def new
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_ADMIN
      @library = Library.new
    else
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    end
  end

  # GET /libraries/1/edit
  def edit
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    when ApplicationController::TYPE_LIBRARIAN
      check = Library.check_if_authorised?(user_type, current_user.id, params[:id]);
      if (check == false)
        flash[:notice] = "You are not authorised to perform this action"
        redirect_to root_path
      end
    when ApplicationController::TYPE_ADMIN
      # admin can edit any library
    end
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to root_url, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    Library.delete(params[:id])
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_library
    @library = Library.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def library_params
    params.require(:library).permit(:name, :location, :max_days, :overdue_fine, :university_id)
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <div class="login-margins-30" style="margin-top: 0%">
    <% if library.errors.any? %>
      <h2 align="center"><%= pluralize(library.errors.count, "error") %></h2>
      <ul class="list-group">
        <% library.errors.full_messages.each do |message| %>
          <li id="alert" class="list-group-item list-group-item-danger" style="text-align: center"><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group card">

      <% if session[:user_type] == ApplicationController::TYPE_ADMIN %>
        <%= form.label :library_name, nil, class: "center-align" %>
        <%= form.text_field :name, class: "form-control" %>

        <%= form.label :library_location, nil, class: "center-align" %>
        <%= form.text_field :location, class: "form-control" %>
      <% end %>

      <%= form.label :library_max_days, nil, class: "center-align" %>
      <%= form.number_field :max_days, class: "form-control" %>

      <%= form.label :library_overdue_fine, nil, class: "center-align" %>
      <%= form.text_field :overdue_fine, class: "form-control" %>

      <% if session[:user_type] == ApplicationController::TYPE_ADMIN %>
        <%= form.label :library_university, nil, class: "center-align" %>
        <%= form.collection_select :university_id, University.all, :id, :name, {}, {class: "form-control"} %>
      <% end %>

    </div>
    <div class="actions">
      <%= form.submit nil, class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<% if session[:user_type] == ApplicationController::TYPE_LIBRARIAN %>
  <%= render html: ("<h1 align='center'>Changing " + @library.name + " Policies</h1>").html_safe %>
<% else %>
  <h1 align="center">Editing Library</h1>
<% end %>

<%= render 'form', library: @library %>

<div class="login-margins-30" style="margin-top: -2em;">
  <%= link_to 'Show',
              @library,
              class: "btn btn-primary btn-block",
              style: "color: #ffffff;" %>
</div>

app/views/libraries/index.html.erb
<% if notice != nil %>
  <h6 id="alert" class="alert alert-info" style="text-align: center; margin-top: 0;"><%= notice %></h6>
<% end %>

<h4 align="center">Libraries</h4>

<div class="card-scrollable">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Max days</th>
      <th>Overdue fine</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.location %></td>
        <td><%= library.max_days %></td>
        <td><%= library.overdue_fine %></td>
        <td>
          <% if session[:user_type] == ApplicationController::TYPE_STUDENT %>
            <%= link_to books_path(:library_id => library.id) do %>
              <i class="glyphicon glyphicon-align-justify" data-toggle="tooltip" title="Browse books"></i>&nbsp;
            <% end %>
          <% else %>
            <%= link_to library do %>
              <i class="glyphicon glyphicon-fullscreen" data-toggle="tooltip" title="Library details"></i>&nbsp;
            <% end %>
            <%= link_to edit_library_path(library) do %>
              <i class="glyphicon glyphicon-edit" data-toggle="tooltip" title="Edit library"></i>&nbsp;
            <% end %>
            <%= link_to library, method: :delete, data: {confirm: 'This will delete all data associated with the library. Are you sure?'} do %>
              <i class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Delete library"></i>&nbsp;
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<% if session[:user_type] == ApplicationController::TYPE_ADMIN %>
  <%= link_to 'Add a new library',
              new_library_path,
              class: "btn btn-primary pull-right",
              style: "color: #ffffff; margin-right: 0;" %>
<% end %>

<br>

app/views/libraries/new.html.erb
<h2 align="center">Create a new library</h2>

<%= render 'form', library: @library %>

app/views/libraries/show.html.erb
<div class="login-margins-30 card">

  <% if notice != nil %>
    <h6 id="alert" class="alert alert-info" style="text-align: center; margin-top: 0;"><%= notice %></h6>
  <% end %>

  <h4 class="div-custom">
    <strong>Name: <%= @library.name %></strong>
  </h4>

  <h4 class="div-custom">
    <strong>Location: <%= @library.location %></strong>
  </h4>

  <h4 class="div-custom">
    <strong>Max days: <%= @library.max_days %></strong>
  </h4>

  <h4 class="div-custom">
    <strong>Overdue fine: <%= @library.overdue_fine %></strong>
  </h4>

  <%= link_to 'Edit',
              edit_library_path(@library),
              class: "btn btn-primary btn-block",
              style: "color: #ffffff;" %>

</div>