config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :book_requests do
    collection do
      post 'approve'
      post 'reject'
    end
  end
  resources :universities
  resources :book_counts
  resources :book_histories do
    collection do
      get 'overdue_fines'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  resources :students
  resources :librarians do
    member do
      get 'approve'
    end
  end
  resources :libraries
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'book_histories/:id/return', to: 'book_histories#return_book'

  root 'home#index'
  # redirecting all undefined routes to homepage for now
  # this prevents the javascript file from being dynamically generated
  # will have to search for another alternative
  # get '*path', to: 'home#index'

  get 'home/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'set_google_signup_user_type', to: 'sessions#set_google_signup_user_type'

  get 'javascripts/dynamic_libraries'

  get '/privacy' => "privacy#show"

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # Redirecting non existing routes to
  get "*path", to: redirect('/')

end

app/models/book_count.rb
class BookCount < ApplicationRecord
  belongs_to :book
  belongs_to :library

  validates :book_id,
            :presence => true
  validates :library_id,
            :presence => true
  validates :book_copies,
            :presence => true,
            :numericality => {greater_than: 0},
            :on => :create

  def self.check_if_available?(book_id, library_id)
    book_count = BookCount.where(:book_id => book_id,
                                 :library_id => library_id).first
    if (book_count.book_copies > 0)
      return true
    else
      return false
    end
  end

  def self.book_count_decrement(book_id, library_id)
    book_count = BookCount.where(:book_id => book_id,
                                 :library_id => library_id).first
    book_count.update(:book_copies => book_count.book_copies - 1)
  end

  def self.book_count_increment(book_id, library_id)
    book_count = BookCount.where(:book_id => book_id,
                                 :library_id => library_id).first
    book_count.update(:book_copies => book_count.book_copies + 1)
  end

  def self.check_if_book_in_use?(book_id)
    count = BookCount.where(:book_id => book_id).count
    if count > 0
      return true
    else
      return false
    end
  end

  def self.fetch_book_counts_by_library(library_id)
    book_counts = BookCount.where(:library_id => library_id)
    return book_counts
  end

  def self.check_if_authorised?(library_id, book_count_id)
    count = BookCount.where(:library_id => library_id,
                            :id => book_count_id).count
    if (count > 0)
      return true
    else
      return false
    end
  end
end

app/controllers/book_counts_controller.rb
class BookCountsController < ApplicationController
  before_action :set_book_count, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /book_counts
  # GET /book_counts.json
  def index
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    when ApplicationController::TYPE_LIBRARIAN
      @book_counts = BookCount.fetch_book_counts_by_library(@current_user.library_id)
    when ApplicationController::TYPE_ADMIN
      @book_counts = BookCount.all
    end
  end

  # GET /book_counts/1
  # GET /book_counts/1.json
  def show
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    when ApplicationController::TYPE_LIBRARIAN
      check = BookCount.check_if_authorised?(current_user.library_id, params[:id])
      if (check == false)
        flash[:notice] = "You are not authorised to perform this action"
        redirect_to root_path
      end
    when ApplicationController::TYPE_ADMIN
      # admin can see any book count
    end
  end

  # GET /book_counts/new
  def new
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    else
      # admin can see any book count
      @book_count = BookCount.new
    end
  end

  # GET /book_counts/1/edit
  def edit
    user_type = session[:user_type]
    case user_type
    when ApplicationController::TYPE_STUDENT
      flash[:notice] = "You are not authorised to perform this action"
      redirect_to root_path
    when ApplicationController::TYPE_LIBRARIAN
      check = BookCount.check_if_authorised?(current_user.library_id, params[:id])
      if (check == false)
        flash[:notice] = "You are not authorised to perform this action"
        redirect_to root_path
      end
    when ApplicationController::TYPE_ADMIN
      # admin can see any book count
    end
  end

  # POST /book_counts
  # POST /book_counts.json
  def create
    @book_count = BookCount.new(book_count_params)
    book_exists = BookCount.exists?(:library_id => book_count_params[:library_id],
                                    :book_id => book_count_params[:book_id])
    respond_to do |format|
      if book_exists
        format.html { redirect_to @book_count, notice: 'This book is already present in the library.' }
      else
        if @book_count.save
          format.html { redirect_to @book_count, notice: 'Book count was successfully created.' }
          format.json { render :show, status: :created, location: @book_count }
        else
          format.html { render :new }
          format.json { render json: @book_count.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /book_counts/1
  # PATCH/PUT /book_counts/1.json
  def update
    respond_to do |format|
      if @book_count.update(book_count_params)
        format.html { redirect_to @book_count, notice: 'Book count was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_count }
      else
        format.html { render :edit }
        format.json { render json: @book_count.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_counts/1
  # DELETE /book_counts/1.json
  def destroy
    @book_count.destroy
    respond_to do |format|
      format.html { redirect_to book_counts_url, notice: 'Book count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book_count
    @book_count = BookCount.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_count_params
    params.require(:book_count).permit(:book_id, :library_id, :book_copies)
  end
end

app/helpers/book_counts_helper.rb
module BookCountsHelper
end

app/views/book_counts/_form.html.erb
<%= form_with(model: book_count, local: true) do |form| %>
  <div class="login-margins-30" style="margin-top: 0%">
    <% if book_count.errors.any? %>
      <h2 align="center"><%= pluralize(book_count.errors.count, "error") %></h2>
      <ul class="list-group">
        <% book_count.errors.full_messages.each do |message| %>
          <li id="alert" class="list-group-item list-group-item-danger" style="text-align: center"><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group card">

      <%= form.label :book_to_add, nil, class: "center-align" %>
      <%= form.collection_select :book_id, Book.all, :id, :title, {include_blank: true}, {class: "form-control"} %>

      <% if session[:user_type] == ApplicationController::TYPE_ADMIN %>
        <%= form.label :library_to_add_the_book_to, nil, class: "center-align" %>
        <%= form.collection_select :library_id, Library.all, :id, :name, {include_blank: true}, {class: "form-control"} %>
      <% end %>

      <% if session[:user_type] == ApplicationController::TYPE_LIBRARIAN %>
        <%= form.label :library_to_add_the_book_to, nil, class: "center-align" %>
        <%= form.collection_select :library_id, Library.where(:id => current_user.library_id), :id, :name, {include_blank: true}, {class: "form-control"} %>
      <% end %>

      <%= form.label :number_of_books, nil, class: "center-align" %>
      <%= form.number_field :book_copies, class: "form-control" %>

    </div>

    <div class="actions">
      <%= form.submit nil, class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/book_counts/edit.html.erb
<h1 align="center">Editing Book Count</h1>

<%= render 'form', book_count: @book_count %>

<div class="login-margins-30" style="margin-top: -2em;">
  <%= link_to 'Show',
              @book_count,
              class: "btn btn-primary btn-block",
              style: "color: #ffffff;" %>
</div>

app/views/book_counts/index.html.erb
<% if notice != nil %>
  <h6 id="alert" class="alert alert-info" style="text-align: center; margin-top: 0;"><%= notice %></h6>
<% end %>

<h4 align="center">Books present in libraries</h4>

<div class="card-scrollable">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Book</th>
      <th>Library</th>
      <th>Count</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @book_counts.each do |book_count| %>
      <tr>
        <td><%= book_count.book.title %></td>
        <td><%= book_count.library.name %></td>
        <td><%= book_count.book_copies %></td>
        <td>
          <%= link_to book_count do %>
            <i class="glyphicon glyphicon-fullscreen" data-toggle="tooltip" title="View details"></i>&nbsp;
          <% end %>
          <%= link_to edit_book_count_path(book_count) do %>
            <i class="glyphicon glyphicon-edit" data-toggle="tooltip" title="Edit details"></i>&nbsp;
          <% end %>
          <%= link_to book_count, method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Delete book from library"></i>&nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Add a book to library',
            new_book_count_path,
            class: "btn btn-primary pull-right",
            style: "color: #ffffff; margin-right: 0;" %>

<br>

app/views/book_counts/new.html.erb
<h2 align="center">Add books to libraries</h2>

<%= render 'form', book_count: @book_count %>

app/views/book_counts/show.html.erb
<div class="login-margins-30 card">

  <% if notice != nil %>
    <h6 id="alert" class="alert alert-info" style="text-align: center; margin-top: 0;"><%= notice %></h6>
  <% end %>

  <h4 class="div-custom">
    <strong>Book: <%= @book_count.book.title %></strong>
  </h4>

  <h4 class="div-custom">
    <strong>Library: <%= @book_count.library.name %></strong>
  </h4>

  <h4 class="div-custom">
    <strong>Count: <%= @book_count.book_copies %></strong>
  </h4>

  <%= link_to 'Edit',
              edit_book_count_path(@book_count),
              class: "btn btn-primary btn-block",
              style: "color: #ffffff;" %>

</div>