config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :book_requests do
    collection do
      post 'approve'
      post 'reject'
    end
  end
  resources :universities
  resources :book_counts
  resources :book_histories do
    collection do
      get 'overdue_fines'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  resources :students
  resources :librarians do
    member do
      get 'approve'
    end
  end
  resources :libraries
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'book_histories/:id/return', to: 'book_histories#return_book'

  root 'home#index'
  # redirecting all undefined routes to homepage for now
  # this prevents the javascript file from being dynamically generated
  # will have to search for another alternative
  # get '*path', to: 'home#index'

  get 'home/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'set_google_signup_user_type', to: 'sessions#set_google_signup_user_type'

  get 'javascripts/dynamic_libraries'

  get '/privacy' => "privacy#show"

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # Redirecting non existing routes to
  get "*path", to: redirect('/')

end

app/models/university.rb
class University < ApplicationRecord
  has_many :libraries
  has_many :librarians
  has_many :students

  validates :name,
            :presence => true
  validates :city,
            :presence => true
  validates :state,
            :presence => true
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /universities
  # GET /universities.json
  def index
    flash[:notice] = "You are not authorised to perform this action"
    redirect_to root_path
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    flash[:notice] = "You are not authorised to perform this action"
    redirect_to root_path
  end

  # GET /universities/new
  def new
    # @university = University.new
    flash[:notice] = "You are not authorised to perform this action"
    redirect_to root_path
  end

  # GET /universities/1/edit
  def edit
    flash[:notice] = "You are not authorised to perform this action"
    redirect_to root_path
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_university
    @university = University.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def university_params
    params.require(:university).permit(:name, :city, :state)
  end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<%= form_with(model: university, local: true) do |form| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
        <% university.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universities</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @universities.each do |university| %>
    <tr>
      <td><%= university.name %></td>
      <td><%= university.city %></td>
      <td><%= university.state %></td>
      <td><%= link_to 'Show', university %></td>
      <td><%= link_to 'Edit', edit_university_path(university) %></td>
      <td><%= link_to 'Destroy', university, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if session[:user_type] == ApplicationController::TYPE_ADMIN %>
  <%= link_to 'New University', new_university_path %>
<% end %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @university.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @university.state %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |