config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :book_requests do
    collection do
      post 'approve'
      post 'reject'
    end
  end
  resources :universities
  resources :book_counts
  resources :book_histories do
    collection do
      get 'overdue_fines'
    end
  end
  resources :books do
    collection do
      get 'filter'
    end
  end
  resources :students
  resources :librarians do
    member do
      get 'approve'
    end
  end
  resources :libraries
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'book_histories/:id/return', to: 'book_histories#return_book'

  root 'home#index'
  # redirecting all undefined routes to homepage for now
  # this prevents the javascript file from being dynamically generated
  # will have to search for another alternative
  # get '*path', to: 'home#index'

  get 'home/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'set_google_signup_user_type', to: 'sessions#set_google_signup_user_type'

  get 'javascripts/dynamic_libraries'

  get '/privacy' => "privacy#show"

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # Redirecting non existing routes to
  get "*path", to: redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library Management System</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="position: relative; min-height: 100vh; padding-bottom: 4em;">
<% if @current_user %>
  <nav class="navbar navbar-inverse" style="background: #444444; border: #444444; border-radius: 0;">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <li><%= link_to "Simple Library", home_index_path, class: "navbar-brand" %></li>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
            <li><a href="/home"><%= @current_user.name %></a></li>
            <li><%= link_to "Logout", logout_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

<div class="margins">
  <div class="login-margins-15" align="center" style="margin-top: 0">
    <% if @current_user %>
      Logged in as <%= current_user.name %>
    <% end %>
  </div>
  <%= yield %>
</div>

<% if @current_user %>
<%# TODO: fix this, make sure it stays at the bottom of the page %>
  <div align="center" class="footer">
    <div style="color: white; padding: 1em;">
      <strong>Library Management System</strong>
    </div>
  </div>
<% end %>

</body>

</html>